### ISSUE TITLE
PRs on tests, coverage, prettier

### ISSUE THREAD

**Issue by gabssnake** [feathericons/feather#174]
Hi, thank you for your work on this, it’s very neat!

Would like to attempt a couple of PR on these Roadmap topics:
[ ] Add tests
[ ] Track code coverage
[ ] Use Prettier to enforce consistent code style

Any preference on tooling? Any particular advice/directions?

**Comment by colebemis** [comment]
Awesome! 🎉  Here are some of my ideas on those Roadmap items:

> Add tests

I'd like to use [Ava](https://github.com/avajs/ava) for testing but I'm open to discussing other options if you have strong opinions. 

I think we should place the tests in the `src` directory like this:

```
src/
  index.js
  to-svg.js
  replace.js
  __tests__/
    index.test.js
    to-svg.test.js
    replace.test.js
```

> Track code coverage

Here's an example of how to track code coverage with Ava: https://github.com/avajs/ava/blob/master/docs/recipes/code-coverage.md

I'd also like to integrate code coverage with GitHub using [Codecov](https://codecov.io).

> Use Prettier to enforce consistent code style

I think we should use [prettier-eslint](https://github.com/prettier/prettier-eslint-cli) because it plays nicely with ESLint. I've been using for my other projects and it works really well. 

When do you think is the best time to automatically format the code? Should we add Prettier formatting as a `precommit` hook?

Ok, I think that's it. Let me know if you have any comments or questions. I'd be more than happy to help. [Twitter](https://twitter.com/colebemis) is probably the easiest way to ask me questions. Also, please let me know how I can improve the contribution process/documention. Thanks!

P.S. You can run `npm run all` in your terminal to get the project all set up. Also, `npm run cm` will help you format your commit messages properly.

**Comment by colebemis** [comment]
I added tests and integrated prettier in v4.0.0 👍
