### ISSUE TITLE
SVG sprite

### ISSUE THREAD

**Issue by Swizz** [feathericons/feather#204]
Hi there, 
I am gonna catch some updates !

Is the SVG sprite still under consideration for a future improvement ?

**Comment by colebemis** [comment]
I've been pretty swamped with school and work. Do you want to open a PR? 

We currently have a node script called `bin/build-svgs.js` that processes all the SVGs from the `icons` direction and puts them in the `dist/icons` directory. To create an SVG sprite, all we should have to do is write a similar `bin/build-sprite.js` script that processes all the SVGs from the `icons` directory and combines them into a `dist/feather-sprite.svg`. You'd also have to do some research on current best practices for SVG sprites (because they change so frequently).

**Comment by wuweiweiwu** [comment]
@colebemis is this still under works? I'd take it :)

**Comment by colebemis** [comment]
@wuweiweiwu I don't think anyone is working on this right now. Feel free to take it on 👍

**Comment by ivanquirino** [comment]
I may start working on this soon, I'm really needing it in sprite form, because I can't stand react-feather's one component per icon approach. I've already made an Icon helper component for using with Open Iconic's sprite so I think I'll follow Open Iconic's approach for the sprite.

**Comment by ivanquirino** [comment]
I made a script that builds the sprite using `dist/icons.json`, so it must be run after the current main build. The SVG attributes of the inner linked file in the `<use />` tag don't work, so the SVG attributes, class or style must be passed when using the inline SVG tag. Just like this:
```html
<svg [feather svg attributes, css class atrtibute, style attribute]>
  <use xlink:href="[spriteFileUrl]#[iconID]"/>
</svg>
```
The following CSS class was extracted from the default icon attributes and renders it nicely:
```css
.feather {
  width: 24px; 
  height: 24px; 
  stroke: currentColor; 
  stroke-width: 2; 
  stroke-linecap: round; 
  stroke-linejoin: round; 
  fill: none
}
```
As today is Saturday and I've had enough alredy, I'll write the tests on Monday and make a PR as soon as possible. The script and SVG file follows:
[build-sprite.zip](https://github.com/feathericons/feather/files/1734224/build-sprite.zip)

**Comment by ivanquirino** [comment]
That's it: https://github.com/feathericons/feather/pull/319

**Comment by colebemis** [comment]
Closed in https://github.com/feathericons/feather/pull/319
