### ISSUE TITLE
Any plans for a larger 48px variation?

### ISSUE THREAD

**Issue by colmtuite** [feathericons/feather#3]
If so, I could maybe start translating some of the icons.

**Comment by colebemis** [comment]
Is there something specific you're looking for in a 48px variation that you can't get by scaling the 24px version by 2x?

Personally, l think the set scales pretty well. (See screenshot)
<img width="826" alt="screen shot 2017-05-16 at 4 08 54 pm" src="https://cloud.githubusercontent.com/assets/4608155/26132068/896e1334-3a52-11e7-8a6f-953493ee26d0.png">

**Comment by colmtuite** [comment]
They scale fine, but I think basic scaling leaves the icons looking a little bland. A larger icon allows for finer detail.

**Comment by colebemis** [comment]
Agreed. I think eventually it would be a great idea to make a custom 48x48 set. Right now, I'm trying to get everything set up to launch v2.0.0 and want to focus on building up a strong core set of 24x24 icons.

I'm going to keep this issue open because I definitely want to revisit this idea later 👍

**Comment by colebemis** [comment]
Closing this issue because I don't plan to make 48x48 icons any time soon. If you're looking for a good 48x48 set Nucleo (https://nucleoapp.com/) and Streamline (http://www.streamlineicons.com/) are both high quality.
