### ISSUE TITLE
Icon Request: Open Folder

### ISSUE THREAD

**Issue by JRiggles** [feathericons/feather#353]
Icon Request: Open Folder

All of the existing folder icons appear as a 'closed' folder. 
An 'Open' folder variant would be useful in things like file trees, upload buttons, etc.

![open-folder-outline_318-41918 1](https://user-images.githubusercontent.com/8763751/37175076-6c637ab8-22e6-11e8-8210-f259c1325f8e.jpg)

**Comment by marcuslindblom** [comment]
I don't know but maybe this is useful?
[folder.svg.zip](https://github.com/feathericons/feather/files/2115027/folder.svg.zip)

**Comment by dotnetcomgazio** [comment]
An other one
[folder-open.zip](https://github.com/feathericons/feather/files/2210284/folder-open.zip)

**Comment by laurensiusadi** [comment]
Here you go @JRiggles 

![open-folder](https://user-images.githubusercontent.com/5661040/43247971-87ce28c6-90e0-11e8-9d9c-0d4df30e5993.png)

Compared to original folder icon:

![folder](https://user-images.githubusercontent.com/5661040/43247902-506d6f72-90e0-11e8-9291-75d5fa70706c.png)

Here's the file

[open-folder.zip](https://github.com/feathericons/feather/files/2230896/open-folder.zip)

**Comment by dotnetcomgazio** [comment]
Sorry, but why is in 32x32 ? all other icons are in 24x24

**Comment by laurensiusadi** [comment]
@dotnetcomgazio sorry, my bad. I was using them for my own project which uses 32x32 to allow more room around the icons I'm using.

Here you go 24x24. I had to change the design a bit to accommodate smaller 24x24 because the previous one designed overflows the boundaries. I hope it helps.

![open-folder-24-4x](https://user-images.githubusercontent.com/5661040/43357145-4b28d8d0-92a7-11e8-8ba7-f743a2f36f47.png)

[open-folder-24.zip](https://github.com/feathericons/feather/files/2238017/open-folder-24.zip)

**Comment by JRiggles** [comment]
Closed. See https://github.com/lucide-icons/lucide/issues/119
