### ISSUE TITLE
Icon Request: Mouse Pointer

### ISSUE THREAD

**Issue by derpmarine168** [feathericons/feather#507]
## Icon Request

* Icon name: Mouse Pointer
* Use case: when you want to represent a user click or a mouse pointer
* Screenshots of similar icons:
![image](https://user-images.githubusercontent.com/28905212/49342048-ae2e8880-f64d-11e8-9874-668c02e2b9ee.png)
![image](https://user-images.githubusercontent.com/28905212/49342052-b5559680-f64d-11e8-8a2f-6f9df69da1a8.png)

**Comment by ashygee** [comment]
<img width="130" alt="screenshot 2019-01-23 22 30 26" src="https://user-images.githubusercontent.com/10384315/51659122-80373780-1f5e-11e9-8f62-8ed8c94f6531.png">

cc @colebemis

**Comment by colebemis** [comment]
Nice! Just to for experimentation sake, can we try a version with a single line stem? Something like this: 

![image](https://user-images.githubusercontent.com/4608155/51724120-b503c700-2010-11e9-811a-785a7a89ed17.png)

https://dribbble.com/shots/3657027-Illustrator-Essentials-Icons

**Comment by ashygee** [comment]
<img width="415" alt="screenshot 2019-01-26 14 36 48" src="https://user-images.githubusercontent.com/10384315/51793610-d92de800-2177-11e9-9796-5c4e82790848.png">

The first two are angled at 30° and the last at 45°. All icons are within the 1px safe zone. I personally like option **A** because I feel it's the most natural and least exaggerated. Because I noticed other icons maintaining a 45° angle for single lines I included option **C** but I don't feel fully confident in this version.

@colebemis thoughts?

**Comment by derpmarine168** [comment]
I personaly think **A**, as it just looks more normal, less out of place.

**Comment by colebemis** [comment]
> I personally think A, as it just looks more normal, less out of place.

I think A looks the most natural because it's a little narrower than B or C. However, I'd kinda like to keep the consistent 45° angle. What about a narrower version of C? Like this:

![image](https://user-images.githubusercontent.com/4608155/51813326-8a14af80-226a-11e9-81c7-13f8d8ede130.png)

@ashygee

**Comment by colebemis** [comment]
Sweet. That’d be awesome! The icon is in our Figma doc.
