### ISSUE TITLE
Slack logo update

### ISSUE THREAD

**Issue by ar-stackrox** [feathericons/feather#516]
## Icon Update Request

Slack has updated its logo in their latest rebrand work - https://brandfolder.com/slack/logos

Could the library update it as well? Thank you!

**Comment by colebemis** [comment]
Thanks for opening this issue. The new Slack logo is on my radar. The new logo is harder to make with Feather's constraints but I'm working on it 👍

**Comment by colebemis** [comment]
@ashygee Looks good! Can you send me the figma file for that?

**Comment by colebemis** [comment]
@ashygee Does that icon have the 1px "safe zone" on the edges? It looks a little bit too big. Here's your version with the "dots" resized to create the 1px "safe zone": 

<img src="https://user-images.githubusercontent.com/4608155/51517807-dd04e780-1dd0-11e9-81b9-3f7e8258128f.png" width="300" />

Here's a before and after from [prisma.io](https://prisma.io):

<img width="1015" alt="screen shot 2019-01-21 at 23 01 10" src="https://user-images.githubusercontent.com/4608155/51517883-176e8480-1dd1-11e9-92f2-4c07eeb18120.png">

<img width="986" alt="screen shot 2019-01-21 at 23 00 53" src="https://user-images.githubusercontent.com/4608155/51517886-19384800-1dd1-11e9-9cce-ff2383f50cb0.png">

I think the old logo worked a little better with Feather's stroke style but the new one's not looking too shabby! :)

**Comment by ashygee** [comment]
@colebemis mine didn't have the 1px safe zone. I looked at some of the older icons such as `video-off` and `users` that went to the edge but I like yours. I had made the dot smaller but wasn't sure about legibility which is why I went for a version where the dot had a 2x2 pixel inside. I agree, the old Slack logo was much better for the Feather suite.

**Comment by ashygee** [comment]
<img width="451" alt="screenshot 2019-01-22 09 45 16" src="https://user-images.githubusercontent.com/10384315/51554571-73192c00-1e2a-11e9-82f2-92d2beb45c13.png">

I updated in Figma to reflect your changes. What do you think?

**Comment by colebemis** [comment]
@ashygee Looks good 👍 Wanna open a PR?

**Comment by colebemis** [comment]
I like the attention to detail! But I think the icon is fine the way it is. The icon is actually rotationally symmetrical because the center of the icon is between the 12th and 13th pixel: 

![image](https://user-images.githubusercontent.com/4608155/51795654-02f90600-219c-11e9-9db9-ef904f331f5a.png)

**Comment by ashygee** [comment]
ok sounds good! I just wanted to double check to avoid any future questions.
